version: '3'

services:
  coin-bot:
    build: .
    image: coin-bot:2.0.7
    environment:
      TG_TOKEN: <token>
    volumes:
      - "./db:/app/db"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
